version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a specific version of the official PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: sprain_vector
      POSTGRES_USER: tony
      POSTGRES_PASSWORD: stark
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - ${DB_HOME}/data/postgres:/var/lib/postgresql/data # Persist data outside the container